# Generated by Django 5.2.16 on 2026-08-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0156_alter_album_image_alter_artist_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpodcast",
            name="is_end_date_inferred",
            field=models.BooleanField(
                default=False,
                help_text="True when end_date is a synthetic estimate (e.g. derived from publication time + duration, or distributed across the sync window) rather than a timestamp backed by real provider listening evidence.",
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="is_end_date_inferred",
            field=models.BooleanField(
                default=False,
                help_text="True when end_date is a synthetic estimate (e.g. derived from publication time + duration, or distributed across the sync window) rather than a timestamp backed by real provider listening evidence.",
            ),
        ),
    ]
