# Generated by Django 5.2.16 on 2026-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0182_episode_order_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="profile_backfill_fail_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="profile_backfill_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="person",
            name="profile_backfill_next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="profile_backfill_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="metadatabackfillstate",
            name="field",
            field=models.CharField(
                choices=[
                    ("runtime", "Runtime"),
                    ("genres", "Genres"),
                    ("credits", "Credits"),
                    ("release", "Release Date"),
                    ("discover", "Discover Metadata"),
                    ("game_lengths", "Game Lengths"),
                    ("trakt_popularity", "Trakt Popularity"),
                    ("igdb_ratings", "IGDB Ratings"),
                    ("watch_providers", "Watch Providers"),
                    ("external_ids", "External IDs"),
                    ("studios", "Studios"),
                    ("imdb_match", "IMDB Title Match"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["source", "profile_backfill_version"],
                name="app_person_source_5f8272_idx",
            ),
        ),
    ]
