# Generated by Django 5.2.16 on 2026-09-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0184_alter_metadatabackfillstate_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatabackfillstate",
            name="field",
            field=models.CharField(
                choices=[
                    ("runtime", "Runtime"),
                    ("genres", "Genres"),
                    ("credits", "Credits"),
                    ("release", "Release Date"),
                    ("discover", "Discover Metadata"),
                    ("game_lengths", "Game Lengths"),
                    ("trakt_popularity", "Trakt Popularity"),
                    ("igdb_ratings", "IGDB Ratings"),
                    ("watch_providers", "Watch Providers"),
                    ("external_ids", "External IDs"),
                    ("studios", "Studios"),
                    ("imdb_match", "IMDB Title Match"),
                    ("status", "Status"),
                    ("tvdb_migration", "TVDB Migration"),
                ],
                max_length=20,
            ),
        ),
    ]
