# Generated by Django 5.2.16 on 2026-08-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0020_koitoaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="jellyfinaccount",
            name="libraries",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cached Jellyfin libraries available for import",
            ),
        ),
        migrations.AddField(
            model_name="jellyfinaccount",
            name="libraries_refreshed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jellyfinaccount",
            name="playback_reporting_available",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the Playback Reporting plugin answered on the last import; null means not probed yet",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jellyfinaccount",
            name="playback_reporting_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
