# Generated by Django 5.2.16 on 2026-08-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0026_psnaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionsourcestate",
            name="source",
            field=models.CharField(
                choices=[
                    ("plex", "Plex"),
                    ("jellyfin", "Jellyfin"),
                    ("radarr", "Radarr"),
                    ("sonarr", "Sonarr"),
                ],
                max_length=20,
            ),
        ),
    ]
