# Generated by Django 5.2.16 on 2026-09-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0031_backfill_collectionsourcestate_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="plexaccount",
            name="section_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-library import settings keyed by '<machine_identifier>::<section_id>', e.g. {'abc::3': {'content_kind': 'audiobook'}}",
            ),
        ),
    ]
