# Generated by Django 5.2.2 on 2026-03-02 16:38

from django.db import migrations, models


# FORK: drift-resilient constraint op per fork migration convention
# (see app/migrations/0053_add_boardgame.py); upstream uses a raw
# AddConstraint here.
def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def populate_list_item_id(apps, schema_editor):
    """Populate list_item_id for existing custom list items ordered by date_added."""
    CustomListItem = apps.get_model('lists', 'CustomListItem')

    custom_list_ids = (
        CustomListItem.objects.values_list('custom_list_id', flat=True)
        .distinct()
    )

    for custom_list_id in custom_list_ids:
        list_items = CustomListItem.objects.filter(custom_list_id=custom_list_id).order_by(
            'date_added',
            'id',
        )
        for index, list_item in enumerate(list_items):
            list_item.list_item_id = index
            list_item.save(update_fields=['list_item_id'])


def reverse_populate_list_item_id(apps, schema_editor):
    """Reverse backfill by resetting list_item_id to null."""
    CustomListItem = apps.get_model('lists', 'CustomListItem')
    CustomListItem.objects.update(list_item_id=None)


class Migration(migrations.Migration):

    # The backfill can queue deferred PostgreSQL FK trigger events. Commit it
    # before adding the unique constraint, otherwise PostgreSQL rejects the
    # ALTER TABLE with "cannot ALTER TABLE ... because it has pending trigger
    # events" (issue #352).
    atomic = False

    dependencies = [
        ('app', '0051_migrate_simkl_periodoc_tasks'),
        ('lists', '0003_alter_customlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlistitem',
            name='list_item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=populate_list_item_id,
            reverse_code=reverse_populate_list_item_id,
        ),
        AddConstraintIfNotExists(
            model_name='customlistitem',
            constraint=models.UniqueConstraint(fields=('custom_list', 'list_item_id'), name='lists_customlistitem_unique_list_item_id'),
        ),
    ]
