# Generated by Django 5.2.16 on 2026-07-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0108_remove_user_tv_sort_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jellyfin_mark_played_enabled",
            field=models.BooleanField(
                default=False, help_text="Process Jellyfin MarkPlayed webhook events"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="jellyfin_mark_unplayed_enabled",
            field=models.BooleanField(
                default=False, help_text="Process Jellyfin MarkUnplayed webhook events"
            ),
        ),
    ]
