# Generated by Django 5.2.16 on 2026-08-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0114_user_premiere_notifications_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="metadata_language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preferred language for TV/movie metadata and cover art. Falls back to the server default when unset.",
                max_length=10,
            ),
        ),
    ]
