# Generated by Django 5.2.16 on 2026-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0118_user_onboarding_selected_sources_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_skipped_integrations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Source slugs whose realtime integration (e.g. a webhook) was explicitly skipped during the setup wizard.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    ("media_types", "Choose Media Types"),
                    ("services", "Choose Services"),
                    ("services_summary", "Review Services"),
                    ("service_setup", "Connect Services"),
                    ("import_status", "Import Status"),
                    ("integration_setup", "Set Up Scrobbling"),
                    ("done", "Done"),
                ],
                default="media_types",
                help_text="Step to resume the first-run setup wizard on.",
                max_length=20,
            ),
        ),
    ]
