# Generated by Django 5.2.16 on 2026-08-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0119_user_onboarding_skipped_integrations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_connected_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Source slugs successfully connected during the setup wizard.",
            ),
        ),
    ]
