# Generated by Django 5.2.16 on 2026-08-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0126_user_pinned_watch_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hardcover_api_key",
            field=models.TextField(
                blank=True,
                help_text="Encrypted personal Hardcover API token, overrides the instance default",
            ),
        ),
    ]
